version: '3.4'

services:
  airflow_dev_container:
    build:
      dockerfile: Dockerfile
      tags:
        - airflow:dev
    image: airflow:dev
    command: airflow standalone
    volumes:
      - $HOME/.config/gcloud/:/var/gcloud:ro
      - ./:/root/airflow
      - ./gcs/:/home/airflow/gcs/
      - $LOCAL_DAGS_FOLDER:/root/airflow/dags
    ports:
      - 3040:3040
    environment:
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT:-in2plane-cloud}
      GOOGLE_APPLICATION_CREDENTIALS: /var/gcloud/application_default_credentials.json
      AIRFLOW__CORE__LOAD_EXAMPLES: FALSE
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 3040
      AIRFLOW__SECRETS__BACKEND: airflow.providers.google.cloud.secrets.secret_manager.CloudSecretManagerBackend
      APP_ENV: ${APP_ENV:-development}
